---
all:
  children:
    linux:
      vars:
        ansible_user: #username
        ansible_password: #password
        ansible_become_user: "root"
        ansible_become_password: #root password
        ansible_become_method: sudo
        become: yes
      children:
        lin:
          hosts:
            10.0.10.130:
    windows:
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_port: 5985
        ansible_become_method: runas
        ansible_user: #Username
        ansible_password: #Password
        ansible_become_user: #Password
        ansible_become_password: #Password
      children:
        win:
          hosts:
            10.0.10.81:
