---
all:
  children:
    linux:
      vars:
        ansible_user: #username
        ansible_password: #password
        ansible_become_user: "root"
        ansible_become_password: #root password
        ansible_become_method: sudo
        become: yes
      children:
        lin:
          hosts:
            10.0.10.130:
    windows:
      vars:
        ansible_psrp_cert_validation: ignore
        ansible_psrp_protocol: https
        ansible_psrp_auth: ntlm
        ansible_psrp_credssp_auth_mechanism: ntlm
        ansible_become_method: runas
        ansible_user: "Admin"
        ansible_password: #Password
        ansible_become_user: "Admin"
        ansible_become_password: #Password
      children:
        win:
          hosts:
            10.0.10.81:
